server:
  port: 8999
spring:
  profiles:
    active: dev
  application:
    name: facedupid-auth-service
  cloud:
    nacos:
      discovery:
        server-addr: 39.105.93.74:8848
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
management:
  endpoints:
    web:
      exposure:
        include: "*"