server:
  port: 8100
spring:
  application:
    name: facedupid-producer-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

management:
  endpoints:
    web:
      exposure:
        include: '*'

# dubbo rpc 配置
dubbo:
  scan:
    base-packages: cn.facedupid.service  # 配置扫描包的路径
  registry:
    address: nacos://127.0.0.1:8848 # 配置注册的地址
  protocol:
    name: dubbo
    port: -1

main:
  allow-bean-definition-overriding: true

# 自定义参数
nacos:
#  address: 39.105.93.74
  address: 127.0.0.1
  port: 8848