server:
  port: 9001

spring:
  application:
    name: facedupid-consumer-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.20:3306/facedupid?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456

mybatis:
  mapper-locations:
    - classpath:dao/*.xml
    - classpath*:cn/facedupid/mapper/*.xml
  type-aliases-package: cn.facedupid.model

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
    fetch-registry: true # 默认为true，集群必须设置为true 才能配合ribbon使用负载均衡
    register-with-eureka: true # 默认为true，表示是否注册到server中
  instance:
    instance-id: consumer
    prefer-ip-address: true

# 设置openFeign的超时，是通过ribbon来实现的，ribbon是负载均衡模块
ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000
# 给指定Service 设置日志级别
logging:
  level:
    cn.facedupid.service.PaymentService: debug
# openFeign 日志